"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv  # type: ignore

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-cskqy2iz=e0@cpmp)t_zee04!bsgcff233mdj69)n!xk9t51o1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#! -> '*' ==> any
ALLOWED_HOSTS = ["*"]


#! Rest authentication and token settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #
    "shares",
    "rest_framework",
    "corsheaders",
]

AUTH_USER_MODEL = "shares.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  #! Cors middleware needs to be placed above CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default":
    # {
    # "ENGINE": "django.db.backends.sqlite3",
    # "NAME": BASE_DIR / "db.sqlite3",
    # }
    {  #!Local PostgreSQL server connection
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("LOCAL_DB_NAME"),  # Your new database name
        "USER": os.environ.get("LOCAL_DB_USER"),  # Your PostgreSQL username
        "PASSWORD": os.environ.get("LOCAL_DB_PASS"),  # Your PostgreSQL password
        "HOST": "localhost",
        "PORT": "5432",
        #! PostgreSQL server connection through IPV6
        # "ENGINE": "django.db.backends.postgresql",
        # "NAME": os.environ.get("DB_NAME", "postgres"),
        # "USER": os.environ.get("DB_USER", "postgres"),
        # "PASSWORD": os.environ.get("DB_PASS"),
        # "HOST": os.environ.get("DB_HOST", "db.zsfxjqehdrdhgwuooaks.supabase.co"),
        # "PORT": os.environ.get("DB_PORT", "5432"),
        #!In case IPV6 connection issue, use the alternative connection details through IPV4
        # "ENGINE": "django.db.backends.postgresql",
        # "NAME": os.environ.get("DB_NAME", "postgres"),
        # "USER": os.environ.get("ALT_DB_USER", "postgres.zsfxjqehdrdhgwuooaks"),
        # "PASSWORD": os.environ.get("DB_PASS"),
        # "HOST": os.environ.get("ALT_DB_HOST", "aws-1-us-east-1.pooler.supabase.com"),
        # "PORT": os.environ.get("DB_PORT", "5432"),
        #! In all cases of connection with external PostgreSQL server (like Supabase)
        # "OPTIONS": {
        # "sslmode": "require",  # Add this line
        # },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Guayaquil"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#! Fix this aftwerwards
CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = [
# "http://localhost:3000",  # React development server
# "http://127.0.0.1:3000",
# ]
CORS_ALLOW_CREDENTIALS = True
