# Generated by Django 5.2.8 on 2025-11-27 06:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('condition', models.CharField(choices=[('shareholder', 'shareholder'), ('authority', 'authority')], default='shareholder', max_length=100)),
                ('wallet_address', models.CharField(default='OX4FE56', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(default='1717241717001', max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_shares', models.IntegerField()),
                ('net_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('retained_earnings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contract_address', models.CharField(default='OXFEA615273', max_length=42, unique=True)),
                ('deployment_tx_hash', models.CharField(blank=True, help_text='Transaction hash of contract deployment', max_length=66, null=True)),
                ('incorporator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_number', models.IntegerField(help_text='Share number (e.g., 1, 2, 3...)')),
                ('share_vpp', models.DecimalField(decimal_places=2, help_text='Valor Patrimonial Proporcional (VPP) - Book value', max_digits=15)),
                ('acquisition_price', models.DecimalField(decimal_places=2, help_text='Actual acquisition cost/price paid', max_digits=15)),
                ('nominal_value', models.DecimalField(decimal_places=2, default=1.0, help_text='Nominal/par value (typically USD $1.00)', max_digits=15)),
                ('acquisition_date', models.DateField(auto_now_add=True)),
                ('token_id', models.CharField(blank=True, help_text='Unique ERC-721 token ID (NFT)', max_length=255, null=True, unique=True)),
                ('minting_tx_hash', models.CharField(blank=True, help_text='Transaction hash when share was minted', max_length=66, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='shares.company')),
                ('shareholder', models.ForeignKey(limit_choices_to={'condition': 'shareholder'}, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'share_number'],
                'unique_together': {('company', 'share_number')},
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('transfer_price', models.DecimalField(decimal_places=2, help_text='Sale price per share', max_digits=15)),
                ('cost_basis_at_transfer', models.DecimalField(blank=True, decimal_places=2, help_text='Tax deductible base captured at time of transfer (immutable)', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('transfer_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='shares.share')),
                ('to_shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
