# Generated by Django 5.2.8 on 2025-11-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_tx_hash',
        ),
        migrations.AddField(
            model_name='share',
            name='minting_timestamp',
            field=models.BigIntegerField(blank=True, help_text='Block timestamp when minted', null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='shareholder_wallet',
            field=models.CharField(blank=True, help_text="Shareholder's Ethereum wallet address", max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='blockchain_timestamp',
            field=models.BigIntegerField(blank=True, help_text='Block timestamp of transfer', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash of blockchain transfer', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='minting_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash of minting', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='token_id',
            field=models.IntegerField(blank=True, help_text='NFT token ID (usually same as share_number)', null=True),
        ),
    ]
